### ISSUE TITLE
wdio-rerun-service appears to be cucumber specific

### ISSUE THREAD

**Issue by ldorval480** [jwplayer/wdio-rerun-service#3]
Unless I'm missing something this  service seems to be cucumber specific?  But your read me suggests it would work for other frameworks.

When running a suite with failing tests I see "Re-run service did not detect any non-passing scenarios." seems to only be checking for non-passing scenarios not non-passing tests.

I've done the setup outlined in the readme, please let me know if I might be missing something.

**Comment by mikesalvia** [comment]
@ldorval480 I will be working to test and convert this to be non-Cucumber specific for the next release. Apologies for the oversight.

**Comment by mikesalvia** [comment]
@ldorval480 Please confirm that version `0.0.5` resolves this issue. To be clear for Jasmine/Mocha Spec files we will be running the entire Spec file at the current time if a failure is seen during testing.

**Comment by mikesalvia** [comment]
I actually have also release `0.0.6` due to a formatting issue in `README.md` both releases should be viable to Mocha/Jasmine.

**Comment by mikesalvia** [comment]
Closing this for now fixed in `0.0.6`.

**Comment by ldorval480** [comment]
@mikesalvia  0.0.6 is not working for me.  I believe you need to define your nonPassingItems array.
I was hoping for a solution that would run only the failing tests, but I see now how that is difficult for Mocha/Jasmine.  Thank you for your quick response.

**Comment by mikesalvia** [comment]
@ldorval480 Issue has been re-opened, perhaps we can work to iterate on a solution for Mocha/Jasmine, I will look into it, it would be figuring out how to integrate into WDIO in some fashion. I will continue to look into the issue with `nonPassingItems` array.

**Comment by mikesalvia** [comment]
Release 0.0.7 today can you try that?

**Comment by ldorval480** [comment]
@mikesalvia Still not working for me.  The property failedExpectations doesn't exist on test.

**Comment by mikesalvia** [comment]
```
afterTest(test, context, { error, result, duration, passed, retries }) {
        if (browser.config.framework !== 'cucumber' && !passed) {
            console.log(`Re-run service is inspecting non-passing test.`);
            console.log(`Test location: ${this.specFile}`);
            this.nonPassingItems.push({ location: this.specFile, failure: test.failedExpectations[0].message });
        }
    }
```
I think what I need to do is just make sure `test` has failedExceptions cause it could be skipped.

**Comment by mikesalvia** [comment]
@ldorval480 Just added a conditional. It would make skipped tests would not have `failedExpectations`.

**Comment by mikesalvia** [comment]
`0.0.8` is live.

**Comment by ldorval480** [comment]
My non passing test still did not contain failedExpectations.  It was not a skipped test.   It looks like your just trying to grab the error message?  Any reason you can't get it out of the error parameter?

**Comment by mikesalvia** [comment]
Let me try that.

**Comment by mikesalvia** [comment]
@ldorval480 You can give `0.0.9` a try it should be live.

**Comment by mikesalvia** [comment]
@ldorval480 Any update on this one?

**Comment by ldorval480** [comment]
@mikesalvia Sorry, been busy.  Its creating the json and rerun script now.  But one issue is the spec file gets added multiple times if there is more than 1 failure in the same spec.

**Comment by mikesalvia** [comment]
All good. I will make sure we add that to uni tests.

**Comment by mikesalvia** [comment]
@ldorval480 The fixes in #10 should fix this.
